### PR TITLE
Fix for #5

### PR DESCRIPTION
**Pull request by ricardopieper**
Added fix and test for fasttext. This allows to load fasttext models when there are multiple words in a line.

Some models have words like this (Universidade de Sao Paulo's NILC embeddings, for instance) that are correctly loaded by libraries like Spacy.

For instance, a line might have "hello there 0.1 0.2 0.3" etc etc. It's not actually the case for NILC, where the actual bug manifests because of a money expression "R$ 0,00"

I think the same work has to be done for the glove, word2vec, etc but here's how I'm doing in my code.

### CODE REVIEW

**Comment by ricardopieper** [comment]
Not sure why the build broke, sorry. For some reason the log file is immense, mostly shows pip downloading stuff.

**Comment by makcedward** [comment]
> Not sure why the build broke, sorry. For some reason the log file is immense, mostly shows pip downloading stuff.

There is some issues on travis-ci. You may ignore it first

**Comment by makcedward** [comment]
> Not sure why the build broke, sorry. For some reason the log file is immense, mostly shows pip downloading stuff.

There is some issue on travis-ci. You may ignore it first

**Comment by makcedward** [comment]
It sounds good. Will accept this merge and updating Word2vecAug and GloVeAug later

**Pull request merged**
